development:
  adapter: postgresql
  encoding: unicode
  database: todo
  pool: 2
  username: deif
  password: holamundo

production:
  adapter: postgresql
  encoding: unicode
  database: todo
  pool: 2
  username: deif
  password: holamundo